name: Release please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Gerar Release Automatica
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ§© Executar Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN}}
          release-type: maven
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true